name = "Minecraft Server With Ash"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f30a03cbe9e757366490937eb89cc687cbf42bc8de0702483b798ab78ad7c3f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
