name = "Minecraft Server With Ash"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b427eb4683b722e23b4d3cac4dd790055d782f0c76849fe00c8efca04cff8b99"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
