name = "Minecraft Server With Ash"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84c79f2b2f0f5d917b18e6a4361a548a7e50779c2638dc77eba6dc41b988d65c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
